packages.json

The kernel-devel package is important for building out-of-tree modules and has a chance of failing to install on an update if layered. Having this package in the base image will ensure that downstream images and users don't get this update issue.

feat: Add kernel-devel package

---

packages.json

Swap mesa-va-drivers and add ffmpeg for full codec support. Packages appear to be broken in F38 which will have to be investigated for enabling in a later change.

feat: swap mesa-va-drivers and add ffmpeg for F37

---

post-install.sh

It seems the cleanup of `Containerfile` and move to scripts like `post-install.sh` resulted in the loss of this command to enable the rpm-ostreed-automatic.timer
This command was dropped from `Containerfile` in https://github.com/ublue-os/main/commit/ee1d4d432b0bcd620894412fa30daf9a556bf8b4
It was not re-added with `post-install.sh` in https://github.com/ublue-os/main/commit/828d71209ee612ccc6373ba76982f63b268d07dc
I'm making the assumption this is a bug since `post-install.sh` retains the update of `/etc/rpm-ostreed.conf` to set `AutomaticUpdatePolicy=stage`.

fix: ostree automatic updates not enabled

---

packages.json

Ok so this appears to be the package desktops use to generate thumbnails, so it should probably go here and not per desktop.  Unsure about how to clean the failed thumbnails out so for now just add this so new installs get it.
Fixes #36

feat: add ffmpegthumbnailer

---

README.md

fix: Reorder und add more info about distrobox to README

fix: Reorder und add more info about distrobox to README

---

README.md
packages.json

Reason for inclusion: Package not available from flathub; hardware enablement.
Add `libratbag-ratbagd` (https://github.com/libratbag/libratbag) to packages, required to configure various mice. A GUI (https://github.com/libratbag/piper) is available from flathub and does not need to be installed in the image, however without ratbagd it is nonfunctional.
Libratbag does not expose any GUI programs to the user and is "invisible" when installed. User which require its functionality are free to install piper from flathub. Its installed size amounts to 336.79 KB.

feat: Include libratbag

---

.github/workflows/release-please.yml

Promote ISO to use F38 ISOs that're now available under the [`releases`](https://dl.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/images/) branch.
The [`:latest`](https://github.com/ublue-os/main/blob/29b429443813c9afc19a301f309f008c41673777/.github/workflows/build.yml#L34) should be updated in a follow-up PR once F38 builds stabilize.

feat: promote ISO to F38 GA

---

.github/workflows/release-please.yml

permission changes were needed when I forked the repo, seems they wouldn't do any harm to have as it makes forking easier
the other change is that now the isogenerator action moves the output to the GITHUB_WORKSPACE as per https://github.com/ublue-os/isogenerator/pull/53 (idk why it started failing with the tagged release)
the related PR needs to be merged first in isogenerator and a new release should be tagged there so the tag here makes sense

feat: use tagged release for isogenerator

---

packages.json

F38 builds are currently blocked due to an issue with [mesa-va-drivers-freeworld](https://bugzilla.rpmfusion.org/show_bug.cgi?id=6612). This change will temporarily disable it for F38 to unblock builds.

fix: temporarily disable mesa-va-drivers-freeworld for f38

---

README.md

We need the full URL so the readme renders correctly on the website.

docs: use full URL for package list

---

.github/workflows/release-please.yml

will trigger rebuild for EFI MOK enrollment fix

fix: bump isogenerator to 1.2.0

---

.github/workflows/build.yml

* The private key for image signing does not need to be stored in the building process. But can be directly accessed from the env. variable.
* Use parameter expansion to store the short sha commit.

refactor: avoid subshell, sign image with env. var

---

.github/workflows/build.yml

F38 builds seem to have stabilized since the release date last week, and many upgrade bugs should be fixed by now.

feat: switch the latest tag to F38

---

.github/workflows/build.yml

The merge queue handles this in one workflow for both PR and merge so we don't need this.

chore(ci): remove building on PR and push

---

.github/workflows/build.yml

The path ignores cause the checks to never finish so we can't merge with this on. Let's just build the world.

chore(ci): remove path ignores

---

packages.json

These are in distro now so we don't need to have these in config either.

feat: add openrgb udev rules

---

post-install.sh

This change is required due to https://github.com/ublue-os/config/pull/39
The ublue-os-update-services RPM was modified to use standard paths agreed on in proposal for standardized locations.
See: https://github.com/orgs/ublue-os/discussions/149

refactor: use new standard path for update-services

---

packages.json

(Upstream repo: https://github.com/lassekongo83/adw-gtk3)
Reasons:
- Users have requested it on Discord and Reddit.
- It's an extremely popular and supremely stable (no glitches) theme, which backports LibAdwaita to GTK3 so that your entire GNOME desktop looks uniform. It's completely neutral and simply makes the desktop look good even when app authors haven't updated their old GTK3 apps yet. It makes the waiting more bearable.
- It's a requirement of the very popular "Gradience" app, which is endorsed by several GNOME devs and allows users to apply accent colors to GNOME's Adwaita theme: https://github.com/GradienceTeam/Gradience
- It's very tedious to have to manually layer such an essential component for most GNOME users. We simplify the user experience by embedding this small theme.
- …

feat: add adw-gtk3-theme for Silverblue

---

packages.json

- "This package contains the tools/ directory from the kernel source and the supporting documentation."
- Helps people debug the kernel and control CPU power states, etc.
- Only 290kb.
Closes #205.

feat: add kernel-tools

---

packages.json

* small CLI tool that provides hardware info
* often used in some instructions on the web

feat: add `lshw` (issue #225)

---

Containerfile
README.md
build.sh

This creates a dependency on https://github.com/ublue-os/akmods/actions for `main` builds.
The resulting `*-main ` images will have the `akmods-ublue.der` pub key installed (via RPM) as well as any akmods built into the akmods RPM cache image.
From main repo's perspective, `akmods` works much like `config` repo, building stuff on upstream `base` before we even start a `main` build.

feat: enable ublue-os akmods

---

Containerfile

This addresses Flatpak installations failing
See: https://github.com/flatpak/flatpak/issues/5452

fix: Revert to older version of ostree to fix Flatpak installations

---

packages.json

Addresses an inconsistency where other images can view thumbnails just fine in their respective file managers, but others can't

feat: Fix inconsistent thumbnails across images

---

Containerfile

No longer needed. Resolved in upstream :)
See: https://bodhi.fedoraproject.org/updates/FEDORA-2023-464fae1680

revert: "fix: Revert to older version of ostree to fix Flatpak installations (#261)"

---

README.md

The README is still showing install instructions for version 37. This is a minor update to refer to the latest version based off Fedora 38

README: update to latest release 38

---

packages.json

Adds the alsa-firmware package needed by a number of different sound cards, including Creative's latest SoundBlaster X AE-5 and AE-7 lines.
Shouldn't conflict with any other packages, just improves OOTB hardware support.

feat: Add alsa-firmware package needed for some sound cards

---

packages.json

[clipman](https://packages.fedoraproject.org/pkgs/clipman/clipman/) is a simple clipboard manager for Wayland
installing it on distrobox or similar doesn't quite work since it needs the reference of the app launches, the only way to make it work is to manually install it, so i think is a small, simple and useful package to have in sericea by default.

feat: add clipman for sericea

---

build.sh

Prevents main from installing every single package provided by ublue-os/akmods
Some kmods have security concerns or are very specific, so they can instead be included downstream.
Resolves #275

fix: Be selective in which kmods are brought into main.

---

packages.json

Currently this prohibits Discover from opening on signed images.
See: https://invent.kde.org/plasma/discover/-/issues/24
To be reverted after this is upstream: 
https://invent.kde.org/ravier/discover/-/commit/927e55f72a4182ef4d3f486849ba3cc57a49fde1

fix(Kinoite): Remove Discover rpm-ostree plugin

---

packages.json

since apparently xwaylandvidebridge is broken on both KDE/GNOME
[kde gitlab](https://invent.kde.org/system/xwaylandvideobridge/-/issues/3l)
[kde forum](https://discuss.kde.org/t/fixing-wayland-xwayland-screen-casting/217/18)

feat: remove xwaylandvideobridge

---

build.sh
github-release-install.sh

The quotes included from the jq string did not behave as normal quotes when used in a bash variable, which resulted in an invalid url string for rpm-ostree install.

fix: use raw output from jq to install cosign again

---

.github/workflows/build.yml

During "Get current version" step, skopeo inspect is failing auth to quay.io with:
> getting username and password: 1 error occurred:\n\t*
> reading JSON file \"/run/containers/1000/auth.json\":
> open /run/containers/1000/auth.json: permission denied
This reverts the builder to `ubuntu-22.04` to mitigate that issue.
This also cleans up some `env.IMAGE_NAME` variable usage to make it less confusing.

fix: switch back to free builders to fix skopeo inspect issue

---

Containerfile
main-packages.json

This is probably temporary until rpmfusion sorts things out but this is to fix all Fedora 38 builds failing with:
```
error: Could not depsolve transaction; 1 problem detected:
Problem: conflicting requests
- package libheif-freeworld-1.15.1-4.fc38.x86_64 from rpmfusion-free requires libheif(x86-64) = 1.15.1, but none of the providers can be installed
- package libheif-freeworld-1.16.1-1.fc38.x86_64 from rpmfusion-free-updates requires libheif(x86-64) = 1.16.1, but none of the providers can be installed
- cannot install both libheif-1.15.1-2.fc38.x86_64 from fedora and libheif-1.16.2-1.fc38.x86_64 from @System
- cannot install both libheif-1.16.1-1.fc38.x86_64 from updates-archive and libheif-1.16.2-1.fc38.x86_64 from @System
```
Also changed the default Containerfile build arg for …

fix: remove libheif-freeworld from packages to fix build

---

main-packages.json
main-post-install.sh

this pr will remove google-noto-sans-cjk-vf-fonts and replace it with google-noto-sans-cjk-fonts
based on https://github.com/ublue-os/bluefin/pull/475

feat: remove google-noto-sans-cjk-vf-fonts and replace it with google-noto-sans-cjk-fonts

---

Containerfile

Downgrade crun to fix compatibility with docker clients
see https://github.com/containers/podman/issues/19930

fix: add workaround for podman/crun regression

---

main-install.sh

Users will still need to layer the remaining openrazer packages, this just provides the driver in kmod form masquerading as the upstream dkms package to satisfy their dependencies.
Depends on: https://github.com/ublue-os/akmods/pull/63

feat: Add OpenRazer kmod

---

.github/workflows/build.yml

This should enable onyx builds for F39 en exclude them from F37 and F38
Closes #196

feat: enable onyx builds

---

main-packages.json

Allows Solaar to be loaded in a distrobox

feat: Add udev rules for Solaar

---

system_files/usr/etc/modprobe.d/default-disable-broadcom-wl.conf

Missing `blacklist ` results in an error running modprobe, plus `wl` driver is getting loaded by default, which is NOT intended.
Fixes bug reported in discord and in original PR for this: https://github.com/ublue-os/main/pull/350#issuecomment-1731654920

fix: add missing blacklist for wl modprobe config

---

main-packages.json

It is frustrating to disable this again already, but it's not building clean.

fix: re-remove libheif-freeworld for F37-F38

---

.github/workflows/build.yml
main-install.sh
nvidia-install.sh

This change selects a specific rpmfusion baseurl rather than using the metalink. During CI builds this will provide more consistent success/fail behavior over the current situation where the mirror metalink is used. This change only impacts the actual build time use in this repo; it is not propagated to user installed images.
Temporarily DISABLES F39 builds in workflow.

chore(ci): use a single rpmfusion mirror for builds (temp disable F39)

---

Containerfile
nokmods-packages.json

Done using a lightly modified upstream spec file for Oversteer that splits the udev rules into their own sub package.

feat: Add udev rules for Logitech steering wheels

---

Containerfile

This adds the bootc binary to the image. It can be used in conjuction with rpm-ostree and will end up on the base image in the future anyway but adding it now so we can test

feat: add a bootc snapshot

---

.github/workflows/build.yml
Containerfile

This was missed when https://github.com/ublue-os/akmods/pull/71 was completed.
Also, shortened workflow job name for easier reading in github UI

fix: use new akmods:main-RELEASE tag structure

---

Containerfile

This has been fixed in podman 4.7.0 https://github.com/containers/podman/issues/19930#issuecomment-1737456096
(draft until it hits stable https://src.fedoraproject.org/rpms/podman)

chore: remove podman workaround

---

install.sh

Should resolve the mismatch between pipewire and the pipewire aptx codec from RPM Fusion
Revert this after pipewire 0.38.2 exits testing

fix(f39): temp: Install pipewire from testing

---

Containerfile

This wasn't hurting our builds since the default value is never used in github actions, but needs to be fixed to avoid confusion for those doing builds by hand (like me).

chore: use correct build-arg default var for SOURCE_ORG

---

packages.json

This had been removed in #358 and not re-added for some time as for several weeks this package was blocking all builds.
Re-adding and hoping for smoother sailing from now on.

feat: re-add libheif-freeworld

---

install.sh
kmods-install.sh

Ah while back, I made a change to akmods/main/nvidia repos to force them to use the same rpmfusion mirror during builds (this gets reset to defaults for resulting images).
This is problematic for F39, since, at the least, it will require a path change due to F39 promoting from "development" to "release".
Only merge after https://github.com/ublue-os/akmods/pull/89 is resolved.

chore: restore default rpmfusion mirror behavior

---

Containerfile
packages.json

This switches us to distro bootc since we should do that anyway and the repo doesn't have 37 anyway.

fix: switch to distro bootc for F38 and F39

---

Containerfile

Added statement to enable automatically booting to a tty for the base image without a DE as per #187.
I hope I've added the statement at the right place. Also, I wasn't sure what the idiomatic way to check for the base image was so I used an if statement. Let me know if I need to change anything. Thanks.

fix: enable boot to tty for base image

---

github-release-install.sh

Sometimes we get seemingly random failures related to curling github APIs in this script. Adding some delay has helped in my personal repo which also uses this script.

chore: longer retry to mitigate occasional issues with github installs

---

.github/workflows/build.yml

Thanks @bobslept for this fix!  Copying from Bluefin to main so the check step always runs - even if a build fails.
Currently a build may fail and as this check step is skipped, we can merge without this check job being successful.
https://github.com/ublue-os/bluefin/pull/696

fix(ci): never skip successful builds check

---

Containerfile

Seeing the package page of Fedora podman 4.8.1 has dropped in the stable branch; https://src.fedoraproject.org/rpms/podman. 
I propose we remove this workaround whenever is viable

chore(podman): Remove the workaround for podman

---

packages.json

this seems to fix F39 builds
this package was already explicitly installed in bazzite. So I guess this is why bazzite didn't break like 2 days ago
```
error: Could not depsolve transaction; 1 problem detected:
Problem: package mesa-va-drivers-freeworld-23.2.1-2.fc39.i686 from rpmfusion-free requires mesa-filesystem(x86-32) = 23.2.1, but none of the providers can be installed
- conflicting requests
- mesa-filesystem-23.2.1-2.fc39.i686 from fedora  does not belong to a distupgrade repository
- package mesa-va-drivers-freeworld-23.2.1-2.fc39.x86_64 from rpmfusion-free requires mesa-filesystem(x86-64) = 23.2.1, but none of the providers can be installed
- cannot install both mesa-filesystem-23.2.1-2.fc39.x86_64 from fedora and mesa-filesystem-23.3.0-1.fc39.x86_64 from @System
```

fix: add mesa-filesystem package

---

install.sh
kmods-install.sh

This consistently pins the build to the same mirror so jobs running on different runners should have the same set of packages to consistently succeed/fail.
This can't succeed until we get a solid build after the merge of https://github.com/ublue-os/akmods/pull/104

chore(ci): pin to single berkley mirror

---

.github/workflows/build.yml

fix: remove lxqt 39 as lazurite replaced it

---

packages.json

Potentially solves an issue where, when rpmfusion is out of date, this will install the 32-bit version of the package and not fail as it should.
As a result, this PR should fail to build until the package is built upstream. We'd rather not update than update w/ broken builds.

fix: Enforce 64-bit version of mesa-va-drivers-freeworld

---

kmods-install.sh

The new xone driver no longer icludes conflicting xpad driver support.

chore: remove now unneeded xpad-noone driver

---

sys_files/usr/lib/systemd/system-generators/ublue-sulogin-generator

This uses a systemd-generator to dyamically write a drop-in config for the rescue and emergency services only when they are requested via the kernel cmdline, which requires console/grub access. This allows use of these modes with the default Fedora state of a password locked root user, but does not auto-allow root access in the case of a failed fsck-check, which can also drop into the emergency shell.
Relates: #470

feat: allow rescue/emergency boot with grub cmdline args

---

install.sh

Prompted by ocf.berkeley being down for a system rebuildand the proven usefulness of using a single mirror, this approach allows local builds with no build-args to work with a default RPMFusion mirror metalink setup, but in case of the build arg (in our CI, a repo variable) RPMFUSION_MIRROR being set, that URL will be substituted as the forced single mirror repo.

chore(ci): conditional pin to repo variable RPMFUSION_MIRROR

---

install.sh

only rename the repo files if we created backups for single mirror
This won't impact current builds since we do use the mirror variable, but it's a more proper experience when not using this.

chore(ci): minor improvement for RPMFUSION_MIRROR

---

install.sh
kmods-install.sh

Enabling rpmfusion-*-updates-testing repos with a lower priority (110 vs the default of 99, as lower is higher priority with yum/dnf/rpm-ostree) such that the testing packages (new mesa version) can get picked up sooner by our builds, but the repo should not be preferred for upgrades unless the version in the repo is specifically required.

chore: enable rpmfusion testing repos

---

github-release-install.sh

A helpful issue was filed with PR which will help address some spurious issues with the github actions workflows. That inspired me to improve the github-release-install.sh script such that it will more properly fail(retry) when http errors occur.
In addition, this includes an improvement to the script which allows installing specific tags, not just the latest release.
Relates: #502

chore(ci): improve retry errors for github installs

---

.github/workflows/build.yml

This is a proposed implementation of #502. It needs to run the GitHub action to be tested, but should improve reliability without manual build re-triggers.

feat: leverage retry-action to increase reliability of builds.

---

.github/workflows/build.yml

This is another in a series of PRs which have been proposed for #502 .
My thought is to identify areas in build_image which have spurious failures and fix them if reasonable within our scripting, or otherwise address issues, like this one.
The idea here is we fix the spurious failures pulling our (very large) base images, by pulling them to the build runner before using the buildah action.

chore(ci): add image pull with retry

---

Containerfile

I'm confused that the original PR ( #488 ) failed to COPY this file via the Containerfile, thus for the last few weeks this has not worked as intended.
Given several people tested it, I'm not sure how we missed that, but this resolves it regardless.

fix: add ublue-sulogin-generatore to image

---

.github/workflows/build.yml

Fedora 40 is branched. In the hopes of getting F40 on day 1, I'm proposing we turn on the image builds for testing but do not mark them as latest/stable. This should not affect existing images even if it fails at first.

chore: attempt to enable Fedora 40 builds

---

.github/workflows/build.yml
install.sh
packages.json

This PR enables F40 `*-main` images builds with minor caveats:
1. The F40 builds are `nokmods` images only, which is the norm since F39.
2. No `mate` images are built since our upstream isn't yet building F40.
**Important note:**
The naming conventions for F40 images (other than silverblue/kinoite) are confusing because of the Fedora naming change to "Atomic Desktop". I may want to discuss this before we start publishing images with wrong names.
Currently we have:
- sericea
- onyx
- lazurite
- mate
- vauxite
Fedora upstream is renaming `sericea` to `sway-atomic` and `onyx` to `budgie-atomic` (or something like that). So I think we should find out what their image names will really be and use that, but I'm open to suggestions.
Also, https://quay.io/organization/fedora-ostree-desktops is …

feat: enable preview of Fedora 40 main builds

---

.github/workflows/release-please.yml

fix: remove vestigial isogenerator

---

Containerfile
install.sh
post-install.sh

I've tried to keep the boilerplate of image building in the Containerfile, while the content and details specific to the image being built is in scripts:
- install.sh
- packages.sh
- post-install.sh
This refactor moves some commands to the scripts which had instead been added to Containerfile.

refactor: keep contents related commands in scripts

---

.github/workflows/reusable-build.yml

Since we don't know when, if ever, the fedora org on quay.io will have reliable images, stop maintaining a conditional which doesn't get used and makes the workflow more complicated.
Relates: #78

chore(ci): drop conditional source logic

---

packages.json

We were only including bootc on Fedora 38 and Fedora 39. This was from a change when we moved from our own packaged version to distro version. This now adds bootc to Fedora 40.

chore: include bootc on all images.

---

packages.json

Revert "chore: include bootc on all images."

---

.gitignore
.vscode/tasks.json
Containerfile
Justfile
just_scripts/build-image.sh
just_scripts/build-iso-installer-main.sh
just_scripts/build-iso-makefile-patch
just_scripts/build-iso.sh
just_scripts/cleanup-dir.sh
just_scripts/cleanup-images.sh
just_scripts/container_mgr.sh
just_scripts/get-defaults.sh
just_scripts/list-images.sh
just_scripts/run-image.sh
just_scripts/run-iso.sh
just_scripts/sudoif.sh

feat(dev): add justfile for local testing and integration with vscode

---

packages.json

This fixes the build, which broke because `ffmpeg-free` was added to the recommends for the `firefox` rpm, which is in the base upstream image:
https://src.fedoraproject.org/rpms/firefox/c/f4c7885a695292c6b3cdffa4239455f1b336307a?branch=rawhide
This means that when uBlue builds the main images and it tries to [remove](https://github.com/ublue-os/main/blob/main/packages.json#L174) `libavcodec-free`, it fails because `libavcodec-free` is a dependency of `ffmpeg-free`, which is now in the base upstream image.
Adding `ffmpeg-free` to the removals list as well, as is done in this PR, allows rpm-ostree to go ahead with the `libavcodec-free` removal by telling it that `ffmpeg-free` should also be removed.

fix: remove ffmpeg-free from all images

---

packages.json

Needed for some workflows, such as having working KeePassXC with Flatpak Firefox

feat: Add flatpak-spawn package by default

---

.github/workflows/reusable-build.yml

This signs the kernel in our images with our akmods key while retaining the signatures of the upstream kernel
There's currently a bug impacting Silverblue users where they are unable to start their systems with SecureBoot enabled. We can work around this by signing the kernel in our main images and requesting that users enroll our akmods key
While this previously only impacted Bluefin, we believe this issue will trickle down to our main images shortly

feat: Sign kernel with our akmods key

---

.github/workflows/build-39.yml
.github/workflows/build-40.yml

Upstream builds build finish at:
2:45am UTC for f40, 3:45am UTC for f39.
This change sets the ublue builds to 20 minutes after upstream

fix: reduce gap between upstream builds and ublue builds

---

.github/workflows/reusable-build.yml

We're using our akmods secret to do this which is not readily available to anyone outside the org

fix(ci): Don't sign kernel on PR

---

sys_files/usr/lib/dracut/dracut.conf.d/10-compression.conf

With this change any regenerated initramfs, either at runtime when configured by a user, or at build time for downstreams like hwe, bazzite, bluefin/aurora, the resulting initramfs image will be compressed with zstd, saving a bit of space.

feat: set dracut zstd compression for initramfs regen

---

.github/workflows/reusable-build.yml
Containerfile
install.sh

feat: use cached kernel

---

.github/pull_request_template.md

https://universal-blue.org/CONTRIBUTING/ responds with a GH 404

docs: fix link to contribution guide in PR template

---

.github/workflows/reusable-build.yml

chore(ci): Ensure image has signed kernels

---

.github/workflows/reusable-build.yml
Containerfile
cleanup.sh
initramfs.sh
install.sh
packages.sh
post-install.sh

chore(ci): Reduce copy layers

---

.github/workflows/reusable-build.yml
Containerfile

This is a small one.  
A fix for a statically referenced repo in the workflow and actually honoring the `IMAGE_REGISTRY` in the Containerfile.

feat(ci): honor `IMAGE_REGISTRY` in Containerfile

---

install.sh

as-is, this changes the srpm repo's priority instead of the rpm repo:
```
[fedora-multimedia-source]
name=negativo17 - Multimedia - Source
baseurl=https://negativo17.org/repos/multimedia/fedora-$releasever/SRPMS
enabled=1
priority=90
```

fix: bug in negativo prioritization command

---

install.sh
packages.json

In #638 we enabled F41 builds without some packages which were still missing in negativo17's fedora-multimedia repo.
Here I re-enable:
- intel-vaapi-driver
- libheif
- pipewire-libs-extra
Note, I'm unsure if libvdpau will ever return given comments here: https://negativo17.org/prime-optimus-laptops-and-multi-gpu-systems/#VDPAU_context

feat: add missing packages to Fedora 41 builds

---

install.sh

Gnome 47/Fedora 41's gnome software app warns users about adding a secure boot MOK for DKMS installed kmods. This seems likely to confuse users of ublue which already provides communication/warnings about how to setup secure boot MOK for our pre-built kmods. Also, dkms is not supported on ublue.
Thanks to @qoijjj for testing this solution.

chore: ensure gnome software doesn't confuse users about dkms MOK

---

packages.json

This includes the missing JPEG-XL and other codec support which is present in F40 Kinoite Builds but not in the F41 builds. Downstream Issue Example: https://github.com/ublue-os/bluefin/issues/1811

fix(kinoite): Include missing KDE image format codecs

---

packages.json

Removes a footgun that prompts users to rebase back to upstream

chore: consistently remove rpm-ostree backend from software stores

---

sys_files/usr/share/dnf/plugins/copr.vendor.conf

This override is to handle the default behavior of dnf5 using ID at /etc/os-release to select which chroot gets used to fetch the copr repo.
An example of the behavior displayed without this override in Bazzite:
```
sudo dnf5 copr enable msmafra/hyprland
https://copr.fedorainfracloud.org/api_3/rpmrepo/msmafra/hyprland/bazzite-41/                        100% | 726.0   B/s | 457.0   B |  00m01s
Chroot not found in the given Copr project (bazzite-41-x86_64).                                                                              You can choose one of the available chroots explicitly:
fedora-40-aarch64
fedora-40-x86_64
fedora-41-aarch64
fedora-41-x86_64
fedora-rawhide-aarch64
fedora-rawhide-x86_64
```

fix: Override copr plugin config to use fedora chroot by default

---

sys_files/usr/share/dnf/plugins/copr.vendor.conf

Resubmission of #663 as per #664

fix: Override copr plugin config to use fedora chroot by default (resubmission)

---

install.sh

Fedora 47 includes a version of gnome-software with a DKMS plugin compiled in. This plugin tries to aid the user by helping setup a MOK for custom kmods, etc... Since Universal Blue has another solution for this which does not include users self-compiling kmods, we needed to disable this.
See: https://copr.fedorainfracloud.org/coprs/ublue-os/staging/package/gnome-software/

feat: Replace gnome-software with non-dkms version on F41 and above.

---

.github/workflows/clean.yml

Cleans everything older than 90 days.

feat(ci): add registry cleanup script

---

packages.json

not shipped by upstream kinoite and also relies on crontabs which is not included in fedora in general

chore: remove kcron package

---

README.md

removes the F39 button from the readme

fix: remove F39 and add F41 build status from README

---

install.sh

It seems a new package was created in Fedora release repos which has started to be installed in all builds of Fedora 41/42, but it was not meant to be installed. The new `OpenCL-ICD-Loader` package conflicts with `ocl-icd` which is required by `mesa-libOpenCL`, nvidia drivers, etc.
This mitigation simply ensures that `ocl-icd` is installed, not the new, undesired package.
Upstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2332429

fix: mitigate OpenCL packaging error

---

.github/workflows/reusable-build.yml
Containerfile

https://github.com/ublue-os/akmods/pull/295 was merged and apparently @bsherman forgot to make needed changes in `main` repo though the appropriate changes were made for Bazzite/Bluefin/Aurora.

fix: remove dependency on kernel images

---

Containerfile

Closes #623 
This should no longer be necessary since the version from the GitHub issue linked above has been released to all images.
@bsherman How do I know if this PR is safe to merge?  I don't think we'll detect this in CI?

chore: remove alternatives workaround

---

Containerfile
install.sh

This addresses merging `config` and `main` repos by simply moving all the RPMs built in `config` to the `packages` repo and building them in COPR. It's cleaner overall.
Relates: #691

refactor: use ublue-os/packages COPR rather than config image

---

install.sh

It's removed by default now & fixes the build fail.

fix(install.sh): There is no need now to manually remove `mesa-libglapi`

---

renovate.json

This will force renovate to pin our deps, will get rid of quite a few attack vectors we ended up running into
https://docs.renovatebot.com/presets-config/#configbest-practices

ci: use best-practices preset for renovate config

---

.github/CODEOWNERS

Reviews on the core ublue-os repos can be slow since they have less traffic than the end-user images.
This proposal adds automated review requests to the ublue-os/approvers on the following repos:
- ublue-os/main (this PR)
- ublue-os/packages
- ublue-os/akmods
The proposal was initially shared in Discord, and has received +1s from Noel, HikariKnight, Tulip and myself, so it would be good to get +1s from a couple other approvers to gain a consensus.

chore: add ublue-os/approvers as CODEOWNERS

---

build_files/post-install.sh

For some reason, `just`’s README file (installed in the `docs` directory from the rpm package) cause an issue where ostree would fail during deployment due to “Pathname can't be converted from UTF-8 to current locale”.
This most commonly shows up when using `build-container-installer` to build an ISO of the image and then install it: https://github.com/JasonN3/build-container-installer/issues/150
As a workaround, we can rename this file to not contain the Chinese characters. This was tested in my own image based on Fedora’s `base-atomic` here: https://github.com/ohaiibuzzle/buzzle-ublue-os

fix: change just's Chinese readme file name to prevent deploy issues

---

packages.json

Unsure if this was purposeful on Fedora's part. But some F41 and F42 images no longer have `/usr/sbin/xauth`. This breaks ssh X forwarding.
Despite most of the ecosystem moving towards Wayland. Xwayland is still an integral part of the Linux Desktop. ssh X forwarding works with Xwayland.
Adding this to all is to ensure that ssh X forwarding works out of the box. It is a restoration of a partially removed feature.

fix: ensure xorg-x11-xauth package is installed

---

build_files/install.sh

Thanks to secureblue:
https://github.com/secureblue/secureblue/pull/976
Those 3 packages need to be in sync with `fedora-multimedia`'s version, or it can happen that GPU video acceleration on Intel stops working.

fix(install.sh): Intel video GPU acceleration

---

build_files/packages.sh
packages.json

packages.sh and packages.json are designed around the behavior of rpm-ostree. Namely, it can install multiple packages while removing multiple packages in a single transaction. `dnf5` does not support this. `dnf5 distro-sync` can bring multiple packages into sync at once, but cannot be used to install packages. `dnf5 swap` only works on one package at a time.
This cleanup removes the behaviour of doing a single transaction of installing and removing. Instead, it parses the the json file to install packages first. Then, it parses the json file and confirms the packages are on image before removing them.
Already merged is a basic package checker for some of the major packages for each image (F42 images only. Lazurite and Vauxite are on their own right now.)
This is a short term change right …

chore: cleanup packages.sh

---

packages.json

Similar to xauth, xhost is on some images and not other images. It is already on kinoite and sway-atomic, but is missing from silverblue and base-main.
xhost can be used to work with permissions for Xwayland. This should be present by default.

chore: Fix missing xhost on some images.

---

.github/workflows/build-40.yml

The base images for these images have been removed from Quay, so builds are failing.  There's nothing we can do about this, so removes them from our build matrix.
Keeps the remaining until they are EOL or are removed from Quay

chore: remove images no longer published by upstream

---

packages.json

Refine (flatpak) does a better job than this, it's time to move to it.

fix(packages): remove gnome-tweaks

---

.github/renovate.json5

I forgot to automerge these akmods updates, so we ended up with a PR needing to be manually merged.
Cancelled the builds to save on runners, merge queue can be skipped here.

fix(ci): group and automerge akmods updates

---

.github/CODEOWNERS

Creates a lot of email spam to ublue members.

chore: remove image-versions from codeowners

---

.github/renovate.json5
.github/workflows/reusable-build.yml
image-versions.yaml

Also allows Renovate to unblock itself when the main branch has had updates.

fix: use digest when extracting kernel versions

---

.github/renovate.json5

Groups the nvidia akmod updates into the regular group to prevent builds from getting stuck

chore(ci): bundle nvidia-akmods updates into images group

---

build_files/nvidia-install.sh

Because of the name change, the nvidia install script failed to install the correct file to allow nvidia to be used with sway.

fix: sway-atomic not getting proper env file on nvidia

---

Justfile

Right now packages.json and other conditions check are not happening due to the passed image name having either a -main or -nvidia suffix.
This strips that to restore previous behavior.

fix: IMAGE_NAME Build arg should not have -main or -nvidia

---

Justfile

This pull request introduces a retry mechanism for pushing container images to a registry. The change ensures that if the `podman push` command fails, it will retry up to five times with an increasing delay between attempts.
* [`Justfile`](diffhunk://#diff-2f90408c2b0302b1cdb7f5d634114750837f940fa82d13057d9c18d0170a7e5cL499-R501): Modified the `push-to-registry` function to include a retry loop for the `podman push` command. If the push fails, it retries up to five times with a delay that increases incrementally (5 seconds, 10 seconds, 15 seconds etc).

chore(ci): retry podman push

---

.devcontainer/Containerfile
.github/renovate.json5

It sends 2-3 emails every day and adds unnecessary commits.

fix: stop renovate from updating dev container

---

build_files/nvidia-install.sh

Prevents the case where nvidia-driver and kmod-nvidia are mismatched, and causes the drivers to fail to start.  This can cause unexpected behaviour, such as boot failure.

fix: ensure kmod-nvidia version matches nvidia-driver

---

.github/workflows/build-beta.yml
.github/workflows/build-gts.yml
.github/workflows/build-latest.yml
Justfile
README.md

- add deprecation notice to README for latest images
- remove deprecated images from GTS builds today
- remove deprecated images from beta builds today
Relates: #927

chore: deprecate images not used by final images

---

packages.json

This reverts commit 4d1a14d9ef25d88e1b59c0b6cf01fde005ec8c89.
this commit breaks qt/sddm/kwin in some way on images starting from `20250611`
a huge chunk of qt stuff updated from `20250610` ->`20250611`
this is definitely an issue on our side as the latest `fedora-ostree-desktops` kinoite 42 image works just fine
a local build with this fix works for me
coredump of kwin_wayland on sddm:
https://gist.github.com/renner0e/db1d25304e29fb1bacf75e4fff949004
how to reproduce:
boot a kinoite-main based image 
diff:

fix: Revert "feat: add fcitx5 packages (#913)"

---

build_files/install.sh
packages.json

This prevents QT package skew, which may crash SDDM/KWin making it impossible to login graphically.
This could happen in scenarios where the base image is still on an old QT version, while the Fedora repositories have newer versions of the QT packages available.
This happened a few days ago when `fcitx*` was updated and the installation of those packages requested the newest version of QT packages, which caused a mismatch between QT and fcitx packages.
More info/how to reproduce:
https://gist.github.com/renner0e/f10300de6abe1c58684262378c0d282a
https://gist.github.com/renner0e/db1d25304e29fb1bacf75e4fff949004

fix: versionlock QT6 and add fcitx packages back

---

build_files/install.sh

kernel-uki-virt seems to be the likely culprit of build issues in main and downstream of main.
Removing it sence it's not actually used in our images given bootc doesn't know how to use it.

fix: remove kernel-uki-virt

---

.github/workflows/reusable-build.yml

SBOMs aren't currently being built, yet we are still running the setup step.
This step often fails with out of storage errors.
This PR disables the unused step.

fix(ci): disable SBOM setup step

---

build_files/post-install.sh

See https://github.com/ublue-os/packages/pull/801 for the description of the problem this fixes
While brew itself isn't present in the `main` image, it's fine to populate the `secure_path` variable with paths that do not exist by default (for example, it already includes `/var/lib/snapd/snap/bin`, when snap is rarely present on a fedora system).
Unlike https://github.com/ublue-os/packages/pull/801, this will not need updating in case the default list of paths gets changed upstream.

feat: add linuxbrew path to sudoers secure_path

---

build_files/install.sh

follow up of:
#1328 
I made some minor changes last time and made a mistake when checking if the correct version of libheif is installed
libheif is preinstalled on kinoite and some other variants but not
silverblue so it would otherwise request a package on silverblue that is
not installed yet, this is why the `--skip-unavailable` is needed.
```
➜  podman run -it localhost/kinoite-main:latest bash
bash-5.2# rpm -qi libheif
Name        : libheif
Epoch       : 1
Version     : 1.19.8
Release     : 1.fc42
Architecture: x86_64
Install Date: Sat Sep 20 17:22:51 2025
Group       : Unspecified
Size        : 2037862
License     : LGPLv3+ and MIT
Signature   : RSA/SHA512, Tue Apr 29 16:38:37 2025, Key ID 97f3008993e8909b
Source RPM  : libheif-1.19.8-1.fc42.src.rpm
Build Date  : Tue Apr 29 12:47:20 …
```

fix: actually swap to negativo libheif
