- README.md
> fix: add usage instructions

- packages.json
Closes https://github.com/ublue-os/main/issues/45
> feat: Add disk management cli tools

- .github/workflows/build.yml
- packages.json
Part of https://github.com/ublue-os/main/issues/38
> feat: Add mate-desktop packages

- packages.json
And move ffmpegthumbnailer to just silverblue, kinoite already has a similar package as confirmed by redtopper in chat. Fixes #55
> feat: add tumbler for thumbnails on sericea

- README.md
Closes #33 
If the instructions here look good, I can add them to https://github.com/ublue-os/website (I'd just need to know where)
> docs: add instructions on how to opt out of updates

- README.md
fix for github markdown flavor
> fix: Readme update 

- packages.json
> feat: add zstd

- .github/workflows/build.yml
A date tag by itself doesn't make sense. I think this removes only that, please review.
> fix: remove standalone date tag

- packages.json
Closes https://github.com/ublue-os/main/issues/79
> feat: Add htop package

- .github/workflows/build.yml
> fix: maintain the current oci version label

- packages.json
> feat: add apr and apr-util

- packages.json
> feat: add intel-media-driver

- .github/workflows/release-please.yml
to avoid error when needing to retry.
> chore(iso): add clobber command

- .github/workflows/release-please.yml
The isogenerator action makes the number now
> chore(iso): remove extra version number

- packages.json
> Revert: "fix: temporarily disable mesa-va-drivers-freeworld for f38"

- packages.json
This is only 116k and we need it for devs. Fixes #60
> feat: add podman-compose

- .github/workflows/build.yml
So we can kick off builds manually
> chore(ci): add workflow dispatch

- packages.json
> feat: add xfce4-clipman-plugin to vauxite

- packages.json
per some chat in discord, this would be nice in main
> feat: add tmux

- .github/ISSUE_TEMPLATE/feature_request.yml
dnf info shows lots of good stuff we should capture, like package size, etc.
> chore(issues): add a field for dnf info on request form

- packages.json
> feat: add xwaylandvideobridge

- packages.json
Stores sh key passwords in KWallet via ssh-add
> Include KSSHAskPass in Kinoite builds

- packages.json
- This package provides the wg binary for controlling WireGuard.
> feat: add wireguard-tools

- CONTRIBUTING.md
This adds a note about how RPM Fusion handles Nvidia driver updates and another note on checks failing in pull requests.
> docs: Update CONTRIBUTING.md with an Nvidia section

- Containerfile
> revert: "revert: "fix: Revert to older version of ostree to fix Flatpak installations (#261)""

- boot_menu.yml
Adding framework entries and missing bluefin entries.
> feat: add bluefin-dx and framework entries to boot menu

- packages.json
> feat(vauxite): add xfce4-whiskermenu-plugin

- .github/workflows/build.yml.save
- .github/workflows/release-please.yml
This bumps isogenerator to v2.1.0
> chore(ci): Bump isogenerator to v2.1.0

- Containerfile
- build.sh
- github-release-install.sh
Adds the cosign command to all ublue `*-main` images.
Relates to #307
> feat: add cosign

- github-release-install.sh
simplify and use jq for a more reliable solution
Thanks @akdev1l for inspiration.
> refactor: improve github-release-install script

- nvidia-install.sh
Needed for Steam games and Wine
> fix(nvidia): Install 32 bit driver libraries

- nvidia-install.sh
> fix(nvidia-32bit): Correct package name

- main-packages.json
libheif-freeworld is building clean again, but not on F39
> feat: restore libheif-freeworld for F37-F38

- main-packages.json
> feat: re-add xwaylandvideobridge

- .github/workflows/build.yml
Wait for https://github.com/ublue-os/akmods/pull/70 to merge
> chore: re-enable f39

- Containerfile
- nokmods-packages.json
Closes https://github.com/ublue-os/config/issues/46
> feat: Add udev rules for android phones

- Containerfile
Why do many copy what one copy do good?
> chore: Minor cleanup

- .github/workflows/build.yml
Somehow #375 merged with very broken CI. This should fix the build at least. Not sure about the merge weirdness.
> chore(ci): fixup CI 

- .github/workflows/build.yml
> feat: turn on F39 for vauxite

- install.sh
This reverts commit b4d73c1eb5e0ff6e740e543ac68c1e0530e194e0.
> Revert "fix(f39): temp: Install pipewire from testing (#396)"

- packages.json
> fix: stop excluding kwrite

- .github/workflows/build.yml
Official images aren't quite ready yet
> fix: Target Fedora 40 for official images, revert 39 to ci-test

- .github/workflows/release-please.yml
Let's kick off Fedora 39 with a new release and new ISOs :)
> chore: release 2.0.0

- packages.json
These were removed during bringup, but should be fine now
> fix(f39): Restore cjk fonts

- packages.json
This doesn't need to be on the main image.
> fix: remove podman-compose

- .github/workflows/build.yml
- packages.json
Planned removal of Fedora 37 due to EOL.
> feat: Fedora 37 is EOL 2023-12-05

- .github/workflows/build.yml
> fix: add lazurite to the build matrix

- packages.json
Address
https://github.com/ublue-os/main/issues/449
> feat: Add Gnome EPUB files thumbnailing support

- .github/workflows/build.yml
> chore(ci): remove space maximizer

- .gitattributes
> fix: add gitattributes file to fix linguist

- .github/workflows/build-38.yml
- .github/workflows/build-39.yml
- .github/workflows/build-40.yml
- .github/workflows/reusable-build.yml
- README.md
this is just meant to cleanup workflow/job naming so it presents better in the actions UI
> chore: streamline naming for github UI

- .github/workflows/reusable-build.yml
bring main into alignment with `hwe` and `bluefin` with concurrency group cancels, etc.
> chore(ci): add concurrency group

- .github/workflows/reusable-build.yml
> chore(ci): Update builder to 24.04

- packages.json
> chore: Have kinoite make avif and webp thumbnails in dolphin

- packages.json
Needed for easy creation of systemd sysextensions
> feat: Add squashfs-tools

- .github/workflows/reusable-build.yml
- Containerfile
- github-release-install.sh
- install.sh
- packages.sh
- post-install.sh
Reverts ublue-os/main#604
Kernel Copy is not working correctly and other downstream breakages occurring.
> Revert "feat: Improve Containerfile / enable workflow usage of containerized buildah (tag: v1)"

- emeritus.md
> feat: create emeritus.md

- packages.json
https://github.com/fedora-silverblue/issue-tracker/issues/589
> fix: Include fuse package for AppImage support

- packages.json
This is tiny, 8.5k and should probably go here and not in bluefin
Fixes: https://github.com/ublue-os/bluefin/issues/1610
> feat: add yubikey-manager

- Containerfile
> feat: Remove lchsh

- packages.json
> feat: add `wl-clipboard` to all images

- .github/workflows/reusable-build.yml
Do not merge until F41 is released.
> Feat: Update tags for F41 Release

- packages.json
https://moritzmolch.com/blog/2502.html
> fix: remove redundant and less performant thumbnailer

- README.md
> chore(readme): Fix links for documentation

- build_files/install.sh
These are all in multimedia F42.
> chore: add intel hw-accel to f42

- .github/workflows/build-42.yml
added cosmic-atomic to build-42.yaml
> feat: add cosmic build

- .github/renovate.json5
> fix(repo): correct automerge casing

- emeritus.md
Part of: https://github.com/ublue-os/main/issues/827
> change: add noelmiller to emeritus

- .github/workflows/build-41.yml
- .github/workflows/build-42.yml
Not sure when we want to land this but renovate is doing a good job and this will save builder time.
> chore(ci): remove scheduled cronjobs

- emeritus.md
> feat: update emeritus.md

- packages.json
Adds fcitx5 packages to the main images.
Closes https://github.com/ublue-os/main/issues/249
> feat: add fcitx5 packages
